import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./nav"

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: [],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
